language: python
dist: xenial
sudo: true

python:
  - 3.9

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VETUALENVS=1

install:
  - pip install -q pipenv
  - pipenv sync -d
  - cp contrib/env-sample .env

script:
  - pipenv run flake8 .
  - pipenv run pytest --cov=pypro

after_success:
  - pipenv run codecov
